name: CI

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim: ['2.0.x', '2.2.x', 'devel']
    steps:
      - uses: actions/checkout@v4
      - name: Install libcurl
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: nimble install -dy
      - name: Run unit tests
        run: nimble test

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker compose up and test
        run: make docker-test
